# Generated by Django 4.2.7 on 2023-12-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
    ]
